version: '3'

services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    env_file:
      - ../.env

  service:
    build: ../movies_admin
    volumes:
      - static_value:/app/staticfiles
    depends_on:
      - db
    env_file:
      - ../.env

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs/site.conf:/etc/nginx/conf.d/site.conf:ro
      - ./data:/data/:ro

      - static_value:/code/staticfiles
      - ../movies_admin:/code
    depends_on:
      - service
    ports:
      - "80:80"

  load_postgres:
    container_name: sqlite_to_postgres
    build:
      context: ../sqlite_to_postgres
    depends_on:
      - nginx
      - service
    env_file:
      - ../.env
    ports:
      - "8888:8888"

  elastic:
    image: elasticsearch:8.6.2
    environment:
      - discovery.type=single-node
      - ingest.geoip.downloader.enabled=false
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    restart: on-failure
    depends_on:
      - load_postgres

  etl:
    build: ../postgres_to_es
    env_file:
      - ../.env
    depends_on:
      - elastic
      - load_postgres
    restart: on-failure


volumes:
  postgres_data:
  static_value: